### ISSUE TITLE
Show optimised list

### ISSUE THREAD

**Issue by elordin** [riedmaph/elisa#223]
### Subtask of #41

- [x] From a list I can choose to optimise by price
- [x] When I choose to do so, the system navigates to an optimised view
- [x] The optimised view shows the optimised list
- [x] The optimised view shows the total saved and the total distance
